find_package(OpenSSL REQUIRED)
if( OpenSSL_FOUND )
    message("Include dir ${OPENSSL_INCLUDE_DIRS}")
    message("OPENSSL_LIBRARIES ${OPENSSL_LIBRARIES}")
    include_directories(${OPENSSL_INCLUDE_DIRS})
    link_directories(${OPENSSL_LIBRARIES})
    message(STATUS "Using OpenSSL ${OPENSSL_VERSION}")
else()
    message(STATUS "SSL not found")
endif()

add_library(libopenssl INTERFACE)
target_include_directories(libopenssl SYSTEM INTERFACE ${OPENSSL_INCLUDE_DIRS})
target_link_libraries(libopenssl INTERFACE ${OPENSSL_LIBRARIES})
